### ISSUE TITLE
TVServerKodi not working with TVServer v1.13.100

### ISSUE THREAD

**Issue by boyelectron** [margro/TVServerXBMC#12]
The Spring16 MP2 update includes TVServer v1.13.100.  It appears that the TVServerKodi plugin (v1.12.0.131) does not work with TVServer 1.13.100 in Windows 7, 64 bit.  For example, telnet localhost 9596 is not able to establish a connection.  Switching back to Summer15 TVServer v1.12.0, telnet localhost 9596 does work.  Does this require an update to the Kodi plugin?

**Comment by margro** [comment]
Yes. see https://www.scintilla.utwente.nl/~marcelg/xbmc/tvserverxbmc.html for a compatible version.
Direct download: [MediaPortal_2_Spring16_TVServerKodi_plugin_rev133.zip](http://dl.dropbox.com/u/7249985/xbmc/tvserverxbmc/MediaPortal_2_Spring16_TVServerKodi_plugin_rev133.zip)
