### ISSUE TITLE
Crash on stopping Mediaportal TvService

### ISSUE THREAD

**Issue by popy2k14** [margro/TVServerXBMC#17]
I am running 1.15.0.137 on tv service 1.15, on stopping the service it crashes with the following exception:

`
[2017-10-10 22:43:54,259] [Log    ] [12       ] [INFO ] - Tvservice stopped due to an unhandled app domain exception System.ObjectDisposedException: Auf das verworfene Objekt kann nicht zugegriffen werden.
Objektname: "System.Net.Sockets.NetworkStream".
   bei System.Net.Sockets.NetworkStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   bei System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
   bei System.IO.StreamWriter.Flush()
   bei TVServerKodi.Commands.DataWriter.write(String line)
   bei TVServerKodi.ConnectionHandler.HandleConnection()
   bei System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   bei System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   bei System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   bei System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   bei System.Threading.ThreadHelper.ThreadStart()
`

Here is the complete log from the event of press "stop" in the service manager: [log_off_stopping.txt](https://github.com/margro/TVServerXBMC/files/1373413/log_off_stopping.txt)

Any hints?

thx
pOpY

**Comment by margro** [comment]
Should be fixed with 1a09807105662d50261d33eb903c70706081ae12

**Comment by popy2k14** [comment]
thx
