### ISSUE TITLE
Media portal 2.2.1

### ISSUE THREAD

**Issue by webby95** [margro/TVServerXBMC#21]
New version of Media Portal. Currently running latest server and 3.5.17.2 client. Hangs on PVR Manager is starting up.

**Comment by margro** [comment]
Should be fixed with: https://github.com/margro/TVServerXBMC/releases/tag/v2.2.1-rev141

**Comment by webby95** [comment]
Thanks so much. I'll give it a try this evening. Well done on your work with these plugins!
