### ISSUE TITLE
TVServerKodi might not work with MediaPortal 2.2.3

### ISSUE THREAD

**Issue by dominicsayers** [margro/TVServerXBMC#23]
I'm a tech professional, but a bit of a n00b when it comes to MediaPortal and Kodi, so you can take what I say here with a big pinch of salt :-)

1. I installed the current version of MediaPortal 2: v2.2.3. All seems well.
2. I installed the current version of TVServerKodi (v1.23.0.143) using [these instructions](https://users.scintilla.utwente.nl/marcelg/xbmc/tvserverxbmc.html)
3. Yes, I restarted the MediaServer 2 Server service twice as instructed.
4. I disabled the Windows 10 firewall

I couldn't get my Kodi instance on another computer to see the TVServerKodi service on port 9596 of the MediaPortal computer.

I ran `nmap` locally on the MediaPortal computer and there was no open port on 9596.

I don't know which logs to look at to see if there was any startup issue but I did do some Googling and it seems there is a fairly tight coupling between MediaPortal versions and this plugin. It seems to be aimed at MediaPortal v2.2.2 so I'm not surprised if it has issues with a later version. I see a similar issue when v2.2.2 was released: https://github.com/margro/TVServerXBMC/issues/22

I wonder if you'd had a chance to test the plugin with MediaPortal 2.2.3?

**Comment by atgr24869** [comment]
I seem to have read that MediaPortal 2.2.3 has reverted the TV Server API to the 2.2.1 version. Try installing the TVServerKodi for 2.2.1 ... let me know ...

**Comment by dominicsayers** [comment]
I'll give this a try and report back. Thanks @atgr24869

**Comment by dominicsayers** [comment]
OK, I tried v1.21.0.141 of the DLL as @atgr24869 suggested and had more success. My Kodi machine can now see the MediaPortal TV server and is showing the EPG as expected.

My one remaining problem is that the TV picture itself for the selected channel is not getting to the Kodi box. I will assume this is a different issue (maybe a firewall blocking the RTSP port or something)

Thanks for the advice!

**Comment by dominicsayers** [comment]
(for posterity I'm noting that the stream wasn't appearing because I hadn't configured the SMB username and password correctly for the MediaPortal server - fixed now)
